
DROP TABLE IF EXISTS PERSON_HOBBIES cascade;;
DROP TABLE IF EXISTS HOBBIES cascade;;
DROP TABLE IF EXISTS PERSONS cascade;;

CREATE TABLE PERSONS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	AGE INT,
	FAVOURITE_COLOR VARCHAR(30)
);;

CREATE TABLE HOBBIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	HOBBY VARCHAR(250) NOT NULL
);;

CREATE TABLE PERSON_HOBBIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	PERSON_ID INT NOT NULL,
	HOBBY_ID INT NOT NULL,
	FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(ID),
	FOREIGN KEY (HOBBY_ID) REFERENCES HOBBIES(ID)
);

